---
title: XTMEM8
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: false
    theme: cerulean
    toc_float: true
    toc: true
    code_folding: show
---
  
******
******

```{r setup, include = F}
rm(list=ls())

# load packages
library(knitr)
library(rmarkdown)
library(broom)
library(tidyverse) 
library(langcog)
library(jsonlite)
library(stringr)
library(png)
library(grid)
library(forcats)
library(effsize)
library(compute.es)


source("../../../analysis/useful_ML.R")

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, cache = F, tidy = F, fig.height = 4)
```  

## Read in and process data
```{r, constants}
EXPTNUM <- 8
a.data.filename <- paste0("exp", EXPTNUM, "_A.csv")
```

```{r, eval = F}
files = dir("../production-results/")
d = data.frame()
for (i in 1:length(files)[1]) {
    s <- fromJSON(paste("../production-results/", files[i], sep = ""))
    s$answers$asses = ifelse(is.null(s$answers$asses), "NA", s$answers$asses)
    d = bind_rows(d, data.frame(s))
}
names(d) <- str_replace(names(d), "answers.", "")
d.anonymized <- anonymize.sids(d, "WorkerId")

write.csv(d.anonymized, a.data.filename)
```

Munge
```{r}
d8 = read.csv(a.data.filename)

d8.long = d8 %>%
  gather(variable, value, contains("_")) %>%
  mutate(trial_num =  unlist(lapply(strsplit(as.character(variable),
                                      "_T"),function(x) x[2])),
         variable = unlist(lapply(strsplit(as.character(variable),
                                      "_"),function(x) x[1]))) %>%
  spread(variable, value) %>%
  mutate(trial_num = as.numeric(trial_num)) %>%
  mutate_if(is.character, funs(as.factor)) 

d8.munged = d8.long %>%
          select(subids, trial_num, category, condition, selected) %>%
          mutate(selected = lapply(str_split(selected, ","), 
                                   function(x) {str_sub(x, 4, 6)})) %>%
          mutate(prop_sub = unlist(lapply(selected, function(x){sum(x == "sub")/2})),
                 prop_bas = unlist(lapply(selected, function(x){sum(x == "bas")/2})),
                 prop_sup = unlist(lapply(selected, function(x){sum(x == "sup")/4}))) %>%
          select(-selected)
```

```{r, eval = F}
d8.munged$exp = EXPTNUM
write.csv(d8.munged, paste0("../../../data/exp", EXPTNUM, "_data_munged.csv"), row.names = F)
```
